repos:
  - repo: local
    hooks:
      - id: clone-overleaf
        name: clone-overleaf
        entry: bash -c 'rm -rf latex && git clone https://git:olp_6CYA7UJ8bd3GebksBVNGiBJMKTXcDq3k144k@git.overleaf.com/6780e2bde2975c5d641bb05d latex && rm -rf latex/.git && git add latex/**'
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
