services:
  bridge:
    build:
      context: ..
      dockerfile: docker/bridge/Dockerfile
    networks:
      drivel_network:
        ipv4_address: 172.16.113.5
    environment:
      - OR_PORT=27797
      - PT_PORT=28483
      - EMAIL=himarc@ethz.ch
      - NICKNAME=DrivelBridgeDev
      - TORBRIDGE_Address=172.16.113.5
    volumes:
      - data-bridge:/var/lib/tor
      - ./.bridgeinfo:/.bridgeinfo
    ports:
      - 27797:27797
      - 28483:28483
    profiles:
      - nodebug
    stop_grace_period: 1s # SIGKILL after 1s
    healthcheck:
      test: [ "CMD-SHELL", "get-bridge-line > /.bridgeinfo && grep -q 'Bootstrapped 100%' /var/log/tor/log" ]
      interval: 2s
      retries: 20
      timeout: 2s
  client:
    build:
      context: ..
      dockerfile: docker/client/Dockerfile
    networks:
      drivel_network:
        ipv4_address: 172.16.113.6
    volumes:
      - data-client:/var/lib/tor
      - ./.bridgeinfo:/.bridgeinfo:ro
    depends_on:
      bridge:
        condition: service_healthy
        restart: true
    profiles:
      - nodebug

  bridge-logs:
    image: busybox
    command: [ /bin/sh, -c, 'tail -n 0 -F /var/lib/tor/pt_state/lyrebird.log' ]
    volumes:
      - data-bridge:/var/lib/tor:ro
    profiles:
      - nodebug
      - debugbridge
    stop_grace_period: 1s # SIGKILL after 1s

  client-logs:
    image: busybox
    command: [ /bin/sh, -c, 'tail -n 0 -F /var/lib/tor/pt_state/lyrebird.log' ]
    volumes:
      - data-client:/var/lib/tor:ro
    profiles:
      - nodebug
    stop_grace_period: 1s # SIGKILL after 1s

  tcpdump:
    image: kaazing/tcpdump
    network_mode: service:client
    volumes:
      - ./tcpdump:/tcpdump
    profiles:
      - nodebug
      - debugbridge

  tcpdump-bridge:
    image: kaazing/tcpdump
    network_mode: service:bridge
    volumes:
      - ./tcpdump-bridge:/tcpdump
    profiles:
      - nodebug
      - debugbridge

  bridge-debugbridge:
    build:
      context: ..
      dockerfile: docker/bridge-debug/Dockerfile
    networks:
      drivel_network:
        ipv4_address: 172.16.113.5
    environment:
      - OR_PORT=27797
      - PT_PORT=28483
      - EMAIL=himarc@ethz.ch
      - NICKNAME=DrivelBridgeDev
      - TORBRIDGE_Address=172.16.113.5
    volumes:
      - data-bridge:/var/lib/tor
      - ./.bridgeinfo:/.bridgeinfo
    ports:
      - 27797:27797
      - 28483:28483
      - 35759:35759
    profiles:
      - debugbridge
    stop_grace_period: 1s # SIGKILL after 1s
    healthcheck:
      test: [ "CMD-SHELL", "cat /var/log/tor/log | grep \"100% (done): Done\"" ]
      interval: 2s
      retries: 20
      timeout: 2s

volumes:
  data-bridge:
    name: tor-datadir-bridge
  data-client:
    name: tor-datadir-client

networks:
  drivel_network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.113.0/24"
