services:
  bridge:
    build:
      context: ..
      dockerfile: docker/bridge/Dockerfile
    networks:
      pq_obfs_network:
        ipv4_address: 172.16.113.5
    environment:
      - OR_PORT=27797
      - PT_PORT=28483
      - EMAIL=himarc@ethz.ch
      - NICKNAME=PqObfsBridgeDev
      - TORBRIDGE_Address=172.16.113.5
    volumes:
      - data:/var/lib/tor
      - ./.bridgeinfo:/.bridgeinfo
    ports:
      - 27797:27797
      - 28483:28483
    profiles:
      - nodebug
    stop_grace_period: 1s # SIGKILL after 1s
    healthcheck:
      test: [ "CMD-SHELL", "get-bridge-line > /.bridgeinfo" ]
      interval: 2s
      retries: 5
      timeout: 2s
  client:
    build:
      context: ..
      dockerfile: docker/client/Dockerfile
    networks:
      pq_obfs_network:
        ipv4_address: 172.16.113.6
    volumes:
      - ./.bridgeinfo:/.bridgeinfo:ro
    depends_on:
      bridge:
        condition: service_healthy
        restart: true
    profiles:
      - nodebug

  bridge-debugbridge:
    build:
      context: ..
      dockerfile: docker/bridge-debug/Dockerfile
    networks:
      pq_obfs_network:
        ipv4_address: 172.16.113.5
    environment:
      - OR_PORT=27797
      - PT_PORT=28483
      - EMAIL=himarc@ethz.ch
      - NICKNAME=PqObfsBridgeDev
      - TORBRIDGE_Address=172.16.113.5
    volumes:
      - data:/var/lib/tor
      - ./.bridgeinfo:/.bridgeinfo
    ports:
      - 27797:27797
      - 28483:28483
      - 35759:35759
    profiles:
      - debugbridge
    stop_grace_period: 1s # SIGKILL after 1s
    healthcheck:
      test: [ "CMD-SHELL", "cat /var/log/tor/log | grep \"100% (done): Done\"" ]
      interval: 2s
      retries: 5
      timeout: 2s

volumes:
  data:
    name: tor-datadir

networks:
  pq_obfs_network:
    ipam:
      driver: default
      config:
        - subnet: "172.16.113.0/24"
